# Generated by Django 5.0.4 on 2024-05-01 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('idenfermedad', models.PositiveIntegerField()),
                ('enfermedad', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('codigo', models.PositiveIntegerField()),
                ('especies', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSector', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('propietario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sectores')),
            ],
        ),
        migrations.AddField(
            model_name='municipios',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias'),
        ),
        migrations.CreateModel(
            name='LetalidadCanina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nuevosBrotes', models.IntegerField()),
                ('nuevosEnfermos', models.IntegerField()),
                ('muertos', models.IntegerField()),
                ('sacrificados', models.IntegerField()),
                ('tratados', models.IntegerField()),
                ('vacunados', models.IntegerField()),
                ('centroInformante', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('enfermedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.enfermedades')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.especies')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sectores')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numOrden', models.IntegerField()),
                ('enfermos', models.IntegerField()),
                ('muertos', models.IntegerField()),
                ('sacrificados', models.IntegerField()),
                ('recuperados', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
            ],
        ),
        migrations.AddField(
            model_name='sectores',
            name='tipoSector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tiposectores'),
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipoAnimal', models.CharField(max_length=50)),
                ('investigaciones', models.TextField(max_length=500)),
                ('provinciaDestino', models.CharField(max_length=50)),
                ('municipioDestino', models.CharField(max_length=50)),
                ('propietarioDestino', models.CharField(max_length=50)),
                ('solicita', models.CharField(max_length=100)),
                ('tramita', models.CharField(max_length=100)),
                ('autoriza', models.CharField(max_length=100)),
                ('nacion', models.CharField(max_length=100)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('municipio_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_uni', to='tasks.municipios')),
                ('provincia_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_uni', to='tasks.provincias')),
            ],
        ),
        migrations.CreateModel(
            name='NotiDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_orden', models.IntegerField()),
                ('codigo_entidad', models.IntegerField()),
                ('codigo_especialista', models.IntegerField()),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('enfermos', models.IntegerField(blank=True, null=True)),
                ('muertos', models.IntegerField(blank=True, null=True)),
                ('sacrificados', models.IntegerField(blank=True, null=True)),
                ('fecha_confeccion', models.DateField()),
                ('fecha_confirmacion', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('municipio', models.ForeignKey(db_column='municipio', on_delete=django.db.models.deletion.CASCADE, to='tasks.municipios')),
                ('propietario', models.ForeignKey(db_column='propietario', on_delete=django.db.models.deletion.CASCADE, to='tasks.propietarios')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.unidad')),
            ],
        ),
    ]
