# Generated by Django 5.0.4 on 2024-05-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notidiaria',
            name='latitud',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
        migrations.AlterField(
            model_name='notidiaria',
            name='longitud',
            field=models.DecimalField(decimal_places=14, max_digits=20),
        ),
    ]
